/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Object3D } from "three";

export function Avatar(props: unknown) {
  const group = useRef<Object3D>(null!);
  const { nodes, materials, animations } = useGLTF("/models/Love.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Mesh_0"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0.geometry}
          material={materials.Material_0}
          position={[0.361, 0.565, -0.092]}
        />
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="meshfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="geo1">
                <mesh
                  name="geo1_principledshader_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.geo1_principledshader_0.geometry}
                  material={materials.principledshader}
                />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="meshfbx001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode001">
              <group name="geo1001">
                <mesh
                  name="geo1_principledshader_0001"
                  castShadow
                  receiveShadow
                  geometry={nodes.geo1_principledshader_0001.geometry}
                  material={materials["principledshader.001"]}
                />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model002" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="meshfbx002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode002">
              <group name="geo1002">
                <mesh
                  name="geo1_principledshader_0002"
                  castShadow
                  receiveShadow
                  geometry={nodes.geo1_principledshader_0002.geometry}
                  material={materials["principledshader.002"]}
                />
              </group>
            </group>
          </group>
        </group>
        <group name="pPlane8" position={[0.067, 0.011, 0]}>
          <mesh
            name="Mesh153"
            castShadow
            receiveShadow
            geometry={nodes.Mesh153.geometry}
            material={materials.mat_AR_glossyBlack}
          />
          <mesh
            name="Mesh153_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh153_1.geometry}
            material={materials["Glow-Ps"]}
          />
          <mesh
            name="pCube10"
            castShadow
            receiveShadow
            geometry={nodes.pCube10.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube100"
            castShadow
            receiveShadow
            geometry={nodes.pCube100.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube101"
            castShadow
            receiveShadow
            geometry={nodes.pCube101.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube102"
            castShadow
            receiveShadow
            geometry={nodes.pCube102.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube103"
            castShadow
            receiveShadow
            geometry={nodes.pCube103.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube104"
            castShadow
            receiveShadow
            geometry={nodes.pCube104.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube105"
            castShadow
            receiveShadow
            geometry={nodes.pCube105.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube106"
            castShadow
            receiveShadow
            geometry={nodes.pCube106.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube107"
            castShadow
            receiveShadow
            geometry={nodes.pCube107.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube108"
            castShadow
            receiveShadow
            geometry={nodes.pCube108.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube109"
            castShadow
            receiveShadow
            geometry={nodes.pCube109.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube11"
            castShadow
            receiveShadow
            geometry={nodes.pCube11.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube110"
            castShadow
            receiveShadow
            geometry={nodes.pCube110.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube111"
            castShadow
            receiveShadow
            geometry={nodes.pCube111.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube112"
            castShadow
            receiveShadow
            geometry={nodes.pCube112.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube113"
            castShadow
            receiveShadow
            geometry={nodes.pCube113.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <group name="pCube114">
            <mesh
              name="Mesh037"
              castShadow
              receiveShadow
              geometry={nodes.Mesh037.geometry}
              material={materials.mat_AR_carcazaBlancaLogo}
            />
            <mesh
              name="Mesh037_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh037_1.geometry}
              material={materials.mat_AR_carcazaBlancaFilos}
            />
          </group>
          <group name="pCube115">
            <mesh
              name="Mesh173"
              castShadow
              receiveShadow
              geometry={nodes.Mesh173.geometry}
              material={materials.mat_AR_carcazaBlanca}
            />
            <mesh
              name="Mesh173_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh173_1.geometry}
              material={materials.mat_AR_carcazaBlancaFilos}
            />
          </group>
          <group name="pCube116">
            <mesh
              name="Mesh069"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069.geometry}
              material={materials.plane}
            />
            <mesh
              name="Mesh069_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_1.geometry}
              material={materials["Glow-Ps"]}
            />
          </group>
          <mesh
            name="pCube117"
            castShadow
            receiveShadow
            geometry={nodes.pCube117.geometry}
            material={materials.mat_AR_glossyBlack}
          />
          <mesh
            name="pCube15"
            castShadow
            receiveShadow
            geometry={nodes.pCube15.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube162"
            castShadow
            receiveShadow
            geometry={nodes.pCube162.geometry}
            material={materials.mat_AR_metal}
          />
          <mesh
            name="pCube18"
            castShadow
            receiveShadow
            geometry={nodes.pCube18.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube20"
            castShadow
            receiveShadow
            geometry={nodes.pCube20.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube21"
            castShadow
            receiveShadow
            geometry={nodes.pCube21.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube22"
            castShadow
            receiveShadow
            geometry={nodes.pCube22.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube23"
            castShadow
            receiveShadow
            geometry={nodes.pCube23.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube24"
            castShadow
            receiveShadow
            geometry={nodes.pCube24.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube25"
            castShadow
            receiveShadow
            geometry={nodes.pCube25.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube26"
            castShadow
            receiveShadow
            geometry={nodes.pCube26.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube27"
            castShadow
            receiveShadow
            geometry={nodes.pCube27.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube28"
            castShadow
            receiveShadow
            geometry={nodes.pCube28.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube29"
            castShadow
            receiveShadow
            geometry={nodes.pCube29.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube30"
            castShadow
            receiveShadow
            geometry={nodes.pCube30.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube31"
            castShadow
            receiveShadow
            geometry={nodes.pCube31.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube32"
            castShadow
            receiveShadow
            geometry={nodes.pCube32.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube33"
            castShadow
            receiveShadow
            geometry={nodes.pCube33.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube34"
            castShadow
            receiveShadow
            geometry={nodes.pCube34.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube35"
            castShadow
            receiveShadow
            geometry={nodes.pCube35.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube36"
            castShadow
            receiveShadow
            geometry={nodes.pCube36.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube37"
            castShadow
            receiveShadow
            geometry={nodes.pCube37.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube38"
            castShadow
            receiveShadow
            geometry={nodes.pCube38.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube39"
            castShadow
            receiveShadow
            geometry={nodes.pCube39.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube40"
            castShadow
            receiveShadow
            geometry={nodes.pCube40.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube41"
            castShadow
            receiveShadow
            geometry={nodes.pCube41.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube42"
            castShadow
            receiveShadow
            geometry={nodes.pCube42.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube43"
            castShadow
            receiveShadow
            geometry={nodes.pCube43.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube44"
            castShadow
            receiveShadow
            geometry={nodes.pCube44.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube45"
            castShadow
            receiveShadow
            geometry={nodes.pCube45.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube46"
            castShadow
            receiveShadow
            geometry={nodes.pCube46.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube47"
            castShadow
            receiveShadow
            geometry={nodes.pCube47.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube48"
            castShadow
            receiveShadow
            geometry={nodes.pCube48.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube49"
            castShadow
            receiveShadow
            geometry={nodes.pCube49.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube50"
            castShadow
            receiveShadow
            geometry={nodes.pCube50.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube51"
            castShadow
            receiveShadow
            geometry={nodes.pCube51.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube55"
            castShadow
            receiveShadow
            geometry={nodes.pCube55.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube56"
            castShadow
            receiveShadow
            geometry={nodes.pCube56.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube64"
            castShadow
            receiveShadow
            geometry={nodes.pCube64.geometry}
            material={materials.mat_AR_metal}
          />
          <mesh
            name="pCube64001"
            castShadow
            receiveShadow
            geometry={nodes.pCube64001.geometry}
            material={materials.mat_AR_metal}
            position={[-0.002, -0.09, 0.027]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.008}
          />
          <mesh
            name="pCube64004"
            castShadow
            receiveShadow
            geometry={nodes.pCube64004.geometry}
            material={materials.mat_AR_metal}
            position={[-0.002, -0.074, 0.028]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.008}
          />
          <mesh
            name="pCube65"
            castShadow
            receiveShadow
            geometry={nodes.pCube65.geometry}
            material={materials.mat_AR_whiteUSB}
            position={[-0.002, -0.09, 0.028]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.008}
          />
          <mesh
            name="pCube65001"
            castShadow
            receiveShadow
            geometry={nodes.pCube65001.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube65004"
            castShadow
            receiveShadow
            geometry={nodes.pCube65004.geometry}
            material={materials.mat_AR_whiteUSB}
            position={[-0.002, -0.074, 0.028]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.008}
          />
          <mesh
            name="pCube66"
            castShadow
            receiveShadow
            geometry={nodes.pCube66.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube67"
            castShadow
            receiveShadow
            geometry={nodes.pCube67.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube68"
            castShadow
            receiveShadow
            geometry={nodes.pCube68.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube69"
            castShadow
            receiveShadow
            geometry={nodes.pCube69.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube70"
            castShadow
            receiveShadow
            geometry={nodes.pCube70.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube71"
            castShadow
            receiveShadow
            geometry={nodes.pCube71.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube72"
            castShadow
            receiveShadow
            geometry={nodes.pCube72.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube73"
            castShadow
            receiveShadow
            geometry={nodes.pCube73.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube74"
            castShadow
            receiveShadow
            geometry={nodes.pCube74.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube75"
            castShadow
            receiveShadow
            geometry={nodes.pCube75.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube76"
            castShadow
            receiveShadow
            geometry={nodes.pCube76.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube77"
            castShadow
            receiveShadow
            geometry={nodes.pCube77.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube78"
            castShadow
            receiveShadow
            geometry={nodes.pCube78.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube79"
            castShadow
            receiveShadow
            geometry={nodes.pCube79.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube80"
            castShadow
            receiveShadow
            geometry={nodes.pCube80.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube81"
            castShadow
            receiveShadow
            geometry={nodes.pCube81.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube82"
            castShadow
            receiveShadow
            geometry={nodes.pCube82.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube83"
            castShadow
            receiveShadow
            geometry={nodes.pCube83.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube84"
            castShadow
            receiveShadow
            geometry={nodes.pCube84.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube85"
            castShadow
            receiveShadow
            geometry={nodes.pCube85.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube86"
            castShadow
            receiveShadow
            geometry={nodes.pCube86.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube87"
            castShadow
            receiveShadow
            geometry={nodes.pCube87.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube88"
            castShadow
            receiveShadow
            geometry={nodes.pCube88.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube89"
            castShadow
            receiveShadow
            geometry={nodes.pCube89.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube9"
            castShadow
            receiveShadow
            geometry={nodes.pCube9.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube90"
            castShadow
            receiveShadow
            geometry={nodes.pCube90.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube91"
            castShadow
            receiveShadow
            geometry={nodes.pCube91.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube92"
            castShadow
            receiveShadow
            geometry={nodes.pCube92.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube93"
            castShadow
            receiveShadow
            geometry={nodes.pCube93.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube94"
            castShadow
            receiveShadow
            geometry={nodes.pCube94.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube95"
            castShadow
            receiveShadow
            geometry={nodes.pCube95.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube96"
            castShadow
            receiveShadow
            geometry={nodes.pCube96.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube97"
            castShadow
            receiveShadow
            geometry={nodes.pCube97.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube98"
            castShadow
            receiveShadow
            geometry={nodes.pCube98.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCube99"
            castShadow
            receiveShadow
            geometry={nodes.pCube99.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCylinder1"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pCylinder2"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder2.geometry}
            material={materials.mat_AR_matteBlack}
          />
          <mesh
            name="pPlane12"
            castShadow
            receiveShadow
            geometry={nodes.pPlane12.geometry}
            material={materials.mat_AR_pureBlack}
          />
          <mesh
            name="pPlane13"
            castShadow
            receiveShadow
            geometry={nodes.pPlane13.geometry}
            material={materials.mat_AR_pureBlack}
          />
          <mesh
            name="pPlane7001"
            castShadow
            receiveShadow
            geometry={nodes.pPlane7001.geometry}
            material={materials.mat_AR_pureBlack}
            position={[-0.002, -0.09, 0.028]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.008}
          />
          <mesh
            name="pPlane7004"
            castShadow
            receiveShadow
            geometry={nodes.pPlane7004.geometry}
            material={materials.mat_AR_pureBlack}
            position={[-0.002, -0.074, 0.028]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.008}
          />
        </group>
        <mesh
          name="pCube65003"
          castShadow
          receiveShadow
          geometry={nodes.pCube65003.geometry}
          material={materials.mat_AR_glossyBlack}
          position={[0.006, 0.023, -0.038]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.008}
        />
        <mesh
          name="pCube65002"
          castShadow
          receiveShadow
          geometry={nodes.pCube65002.geometry}
          material={materials.mat_AR_glossyBlack}
          position={[0.006, 0.005, -0.038]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.008}
        />
        <mesh
          name="pCube164"
          castShadow
          receiveShadow
          geometry={nodes.pCube164.geometry}
          material={materials.mat_AR_metal}
          position={[0, 0.011, 0]}
        />
        <mesh
          name="pCube163"
          castShadow
          receiveShadow
          geometry={nodes.pCube163.geometry}
          material={materials.mat_AR_matteBlack}
          position={[0, 0.011, 0]}
        />
        <group
          name="pCube152001"
          position={[0.386, 0.063, 0.197]}
          rotation={[1.098, 0.161, -0.303]}
          scale={0.006}
        >
          <mesh
            name="Mesh138"
            castShadow
            receiveShadow
            geometry={nodes.Mesh138.geometry}
            material={materials.mat_AR_controllerWhite}
          />
          <mesh
            name="Mesh138_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh138_1.geometry}
            material={materials.mat_AR_led}
          />
          <mesh
            name="botonesPlastico"
            castShadow
            receiveShadow
            geometry={nodes.botonesPlastico.geometry}
            material={materials.mat_AR_transPlastic}
            position={[0.58, 0.649, -0.506]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="flechasPlastico"
            castShadow
            receiveShadow
            geometry={nodes.flechasPlastico.geometry}
            material={materials.mat_AR_transPlastic}
            position={[-1.559, 0.806, -0.302]}
            rotation={[-1.385, 1.485, 1.595]}
          />
          <mesh
            name="pCube122"
            castShadow
            receiveShadow
            geometry={nodes.pCube122.geometry}
            material={materials.mat_AR_buttonSquare}
            position={[0.588, 0.826, -0.473]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube122001"
            castShadow
            receiveShadow
            geometry={nodes.pCube122001.geometry}
            material={materials.mat_AR_buttonSquare}
            position={[0.588, -10.197, -6.451]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube124"
            castShadow
            receiveShadow
            geometry={nodes.pCube124.geometry}
            material={materials.mat_AR_buttonTriangle}
            position={[0.586, -10.191, -6.448]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube124001"
            castShadow
            receiveShadow
            geometry={nodes.pCube124001.geometry}
            material={materials.mat_AR_buttonTriangle}
            position={[0.586, 0.832, -0.469]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube125001"
            castShadow
            receiveShadow
            geometry={nodes.pCube125001.geometry}
            material={materials.mat_AR_transPlastic}
            position={[0.58, -10.374, -6.485]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube126"
            castShadow
            receiveShadow
            geometry={nodes.pCube126.geometry}
            material={materials.mat_AR_buttonCircle}
            position={[0.58, 0.649, -0.506]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube126001"
            castShadow
            receiveShadow
            geometry={nodes.pCube126001.geometry}
            material={materials.mat_AR_buttonCircle}
            position={[0.58, -10.374, -6.485]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube127"
            castShadow
            receiveShadow
            geometry={nodes.pCube127.geometry}
            material={materials.mat_AR_buttonX}
            position={[0.577, 0.819, -0.472]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube127001"
            castShadow
            receiveShadow
            geometry={nodes.pCube127001.geometry}
            material={materials.mat_AR_buttonX}
            position={[0.577, -10.204, -6.45]}
            rotation={[0.2, 0.001, -0.031]}
          />
          <mesh
            name="pCube129"
            castShadow
            receiveShadow
            geometry={nodes.pCube129.geometry}
            material={materials.mat_AR_controllerWhite}
            position={[1.431, 0, 0]}
            rotation={[-0.024, -0.166, 0.082]}
          />
          <mesh
            name="pCube129001"
            castShadow
            receiveShadow
            geometry={nodes.pCube129001.geometry}
            material={materials.mat_AR_controllerWhite}
            position={[1.431, -11.023, -5.979]}
            rotation={[-0.024, -0.166, 0.082]}
          />
          <mesh
            name="pCube129002"
            castShadow
            receiveShadow
            geometry={nodes.pCube129002.geometry}
            material={materials.mat_AR_controllerWhite}
            position={[-26.431, -11.333, 3.79]}
            rotation={[-1.074, 0.815, 0]}
            scale={166.667}
          />
          <mesh
            name="pCube129003"
            castShadow
            receiveShadow
            geometry={nodes.pCube129003.geometry}
            material={materials.mat_AR_controllerWhite}
            position={[-26.431, -11.333, 3.79]}
            rotation={[-1.074, 0.815, 0]}
            scale={166.667}
          />
          <mesh
            name="pCube130"
            castShadow
            receiveShadow
            geometry={nodes.pCube130.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, 0.806, -0.302]}
            rotation={[0.21, 0.002, 0.086]}
          />
          <mesh
            name="pCube130001"
            castShadow
            receiveShadow
            geometry={nodes.pCube130001.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, -10.217, -6.28]}
            rotation={[0.21, 0.002, 0.086]}
          />
          <mesh
            name="pCube131"
            castShadow
            receiveShadow
            geometry={nodes.pCube131.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, -10.217, -6.28]}
            rotation={[-1.385, 1.485, 1.595]}
          />
          <mesh
            name="pCube131001"
            castShadow
            receiveShadow
            geometry={nodes.pCube131001.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, 0.806, -0.302]}
            rotation={[-1.385, 1.485, 1.595]}
          />
          <mesh
            name="pCube132"
            castShadow
            receiveShadow
            geometry={nodes.pCube132.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, -10.217, -6.28]}
            rotation={[-2.931, -0.002, 3.056]}
          />
          <mesh
            name="pCube132001"
            castShadow
            receiveShadow
            geometry={nodes.pCube132001.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, 0.806, -0.302]}
            rotation={[-2.931, -0.002, 3.056]}
          />
          <mesh
            name="pCube133"
            castShadow
            receiveShadow
            geometry={nodes.pCube133.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, -10.217, -6.28]}
            rotation={[1.757, -1.485, 1.546]}
          />
          <mesh
            name="pCube133001"
            castShadow
            receiveShadow
            geometry={nodes.pCube133001.geometry}
            material={materials.mat_AR_boton_flechas}
            position={[-1.559, 0.806, -0.302]}
            rotation={[1.757, -1.485, 1.546]}
          />
          <mesh
            name="pCube134"
            castShadow
            receiveShadow
            geometry={nodes.pCube134.geometry}
            material={materials.mat_AR_transPlastic}
            position={[-1.559, -10.217, -6.28]}
            rotation={[0.21, 0.002, 0.086]}
          />
          <mesh
            name="pCube135"
            castShadow
            receiveShadow
            geometry={nodes.pCube135.geometry}
            material={materials.mat_AR_transPlastic}
            position={[-1.559, -10.217, -6.28]}
            rotation={[-1.385, 1.485, 1.595]}
          />
          <mesh
            name="pCube136"
            castShadow
            receiveShadow
            geometry={nodes.pCube136.geometry}
            material={materials.mat_AR_transPlastic}
            position={[-1.559, -10.217, -6.28]}
            rotation={[-2.931, -0.002, 3.056]}
          />
          <mesh
            name="pCube137"
            castShadow
            receiveShadow
            geometry={nodes.pCube137.geometry}
            material={materials.mat_AR_transPlastic}
            position={[-1.559, -10.217, -6.28]}
            rotation={[1.757, -1.485, 1.546]}
          />
          <mesh
            name="pCube138"
            castShadow
            receiveShadow
            geometry={nodes.pCube138.geometry}
            material={materials.mat_AR_controllerBlack}
            rotation={[0.235, 0, 0]}
          />
          <mesh
            name="pCube138001"
            castShadow
            receiveShadow
            geometry={nodes.pCube138001.geometry}
            material={materials.mat_AR_controllerBlack}
            position={[0, -11.023, -5.979]}
            rotation={[0.235, 0, 0]}
          />
          <mesh
            name="pCube139"
            castShadow
            receiveShadow
            geometry={nodes.pCube139.geometry}
            material={materials.mat_AR_controllerBlack}
            rotation={[0.235, 0, 0]}
          />
          <mesh
            name="pCube139001"
            castShadow
            receiveShadow
            geometry={nodes.pCube139001.geometry}
            material={materials.mat_AR_controllerBlack}
            position={[0, -11.023, -5.979]}
            rotation={[0.235, 0, 0]}
          />
          <mesh
            name="pCube140"
            castShadow
            receiveShadow
            geometry={nodes.pCube140.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube140001"
            castShadow
            receiveShadow
            geometry={nodes.pCube140001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube141"
            castShadow
            receiveShadow
            geometry={nodes.pCube141.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube141001"
            castShadow
            receiveShadow
            geometry={nodes.pCube141001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube142"
            castShadow
            receiveShadow
            geometry={nodes.pCube142.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube142001"
            castShadow
            receiveShadow
            geometry={nodes.pCube142001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube143"
            castShadow
            receiveShadow
            geometry={nodes.pCube143.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube143001"
            castShadow
            receiveShadow
            geometry={nodes.pCube143001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube144"
            castShadow
            receiveShadow
            geometry={nodes.pCube144.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube144001"
            castShadow
            receiveShadow
            geometry={nodes.pCube144001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube145"
            castShadow
            receiveShadow
            geometry={nodes.pCube145.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube145001"
            castShadow
            receiveShadow
            geometry={nodes.pCube145001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube146"
            castShadow
            receiveShadow
            geometry={nodes.pCube146.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube146001"
            castShadow
            receiveShadow
            geometry={nodes.pCube146001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube147"
            castShadow
            receiveShadow
            geometry={nodes.pCube147.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube147001"
            castShadow
            receiveShadow
            geometry={nodes.pCube147001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube148"
            castShadow
            receiveShadow
            geometry={nodes.pCube148.geometry}
            material={materials.mat_AR_pureBlack}
            position={[1.431, -11.176, -5.442]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube148001"
            castShadow
            receiveShadow
            geometry={nodes.pCube148001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[1.431, -0.153, 0.537]}
            rotation={[0.266, 0, 0]}
          />
          <mesh
            name="pCube149"
            castShadow
            receiveShadow
            geometry={nodes.pCube149.geometry}
            material={materials.mat_AR_controllerBlack}
            position={[0, -11.023, -5.979]}
            rotation={[0.756, 0, 0]}
          />
          <group name="pCube149001" rotation={[0.756, 0, 0]}>
            <mesh
              name="Mesh158"
              castShadow
              receiveShadow
              geometry={nodes.Mesh158.geometry}
              material={materials.mat_AR_controllerBlack}
            />
            <mesh
              name="Mesh158_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh158_1.geometry}
              material={materials.mat_AR_led}
            />
          </group>
          <mesh
            name="pCube150"
            castShadow
            receiveShadow
            geometry={nodes.pCube150.geometry}
            material={materials.mat_AR_matteBlack}
            position={[8.507, -36.961, -30.286]}
            rotation={[1.806, 0, -2.911]}
            scale={1.8}
          />
          <mesh
            name="pCube150001"
            castShadow
            receiveShadow
            geometry={nodes.pCube150001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[-8.507, -36.947, -30.344]}
            rotation={[-1.336, 0, -2.911]}
            scale={-1.8}
          />
          <mesh
            name="pCube150002"
            castShadow
            receiveShadow
            geometry={nodes.pCube150002.geometry}
            material={materials.mat_AR_matteBlack}
            position={[8.507, -25.938, -24.307]}
            rotation={[1.806, 0, -2.911]}
            scale={1.8}
          />
          <mesh
            name="pCube150003"
            castShadow
            receiveShadow
            geometry={nodes.pCube150003.geometry}
            material={materials.mat_AR_matteBlack}
            position={[-8.507, -25.924, -24.365]}
            rotation={[-1.336, 0, -2.911]}
            scale={-1.8}
          />
          <mesh
            name="pCube151"
            castShadow
            receiveShadow
            geometry={nodes.pCube151.geometry}
            material={materials.mat_AR_matteBlack}
            position={[8.507, -36.961, -30.286]}
            rotation={[1.446, -0.083, -2.926]}
            scale={1.8}
          />
          <mesh
            name="pCube151001"
            castShadow
            receiveShadow
            geometry={nodes.pCube151001.geometry}
            material={materials.mat_AR_matteBlack}
            position={[8.507, -25.938, -24.307]}
            rotation={[1.446, -0.083, -2.926]}
            scale={1.8}
          />
          <mesh
            name="pCube151002"
            castShadow
            receiveShadow
            geometry={nodes.pCube151002.geometry}
            material={materials.mat_AR_matteBlack}
            position={[-7.771, -26.628, -21.305]}
            rotation={[-1.696, -0.083, -2.926]}
            scale={-1.8}
          />
          <mesh
            name="pCube151003"
            castShadow
            receiveShadow
            geometry={nodes.pCube151003.geometry}
            material={materials.mat_AR_matteBlack}
            position={[-7.771, -37.651, -27.283]}
            rotation={[-1.696, -0.083, -2.926]}
            scale={-1.8}
          />
          <group name="pCube152" position={[0, -11.023, -5.979]}>
            <mesh
              name="Mesh064"
              castShadow
              receiveShadow
              geometry={nodes.Mesh064.geometry}
              material={materials.mat_AR_controllerWhite}
            />
            <mesh
              name="Mesh064_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh064_1.geometry}
              material={materials.mat_AR_led}
            />
          </group>
          <mesh
            name="pCube154"
            castShadow
            receiveShadow
            geometry={nodes.pCube154.geometry}
            material={materials.mat_AR_controllerBlack}
            rotation={[0.235, 0, 0]}
          />
          <mesh
            name="pCube154001"
            castShadow
            receiveShadow
            geometry={nodes.pCube154001.geometry}
            material={materials.mat_AR_controllerBlack}
            position={[0, -11.023, -5.979]}
            rotation={[0.235, 0, 0]}
          />
          <group name="pCube155" rotation={[0.235, 0, 0]}>
            <mesh
              name="Mesh118"
              castShadow
              receiveShadow
              geometry={nodes.Mesh118.geometry}
              material={materials.mat_AR_controllerBlack}
            />
            <mesh
              name="Mesh118_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh118_1.geometry}
              material={materials.mat_AR_controllerWhite}
            />
          </group>
          <group
            name="pCube155001"
            position={[0, -11.023, -5.979]}
            rotation={[0.235, 0, 0]}
          >
            <mesh
              name="Mesh134"
              castShadow
              receiveShadow
              geometry={nodes.Mesh134.geometry}
              material={materials.mat_AR_controllerBlack}
            />
            <mesh
              name="Mesh134_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh134_1.geometry}
              material={materials.mat_AR_controllerWhite}
            />
          </group>
          <mesh
            name="pCube156"
            castShadow
            receiveShadow
            geometry={nodes.pCube156.geometry}
            material={materials.mat_AR_controllerBlack}
            rotation={[-2.906, 0, 0]}
          />
          <mesh
            name="pCube156001"
            castShadow
            receiveShadow
            geometry={nodes.pCube156001.geometry}
            material={materials.mat_AR_controllerBlack}
            position={[0, -11.023, -5.979]}
            rotation={[-2.906, 0, 0]}
          />
          <group
            name="pCube158"
            position={[-26.431, -11.333, 3.79]}
            rotation={[0.497, 0, 0]}
            scale={166.667}
          >
            <mesh
              name="Mesh114"
              castShadow
              receiveShadow
              geometry={nodes.Mesh114.geometry}
              material={materials.mat_AR_carcazaBlancaFilos}
            />
            <mesh
              name="Mesh114_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh114_1.geometry}
              material={materials.mat_AR_led}
            />
            <mesh
              name="Mesh114_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh114_2.geometry}
              material={materials.mat_AR_glossyBlack}
            />
            <mesh
              name="Mesh114_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh114_3.geometry}
              material={materials.lambert1}
            />
          </group>
          <group name="svgMesh3" rotation={[0.43, 0, 0]}>
            <mesh
              name="Mesh019"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019.geometry}
              material={materials.mat_AR_led}
            />
            <mesh
              name="Mesh019_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh019_1.geometry}
              material={materials.mat_AR_controllerBlack}
            />
          </group>
          <mesh
            name="svgMesh3001"
            castShadow
            receiveShadow
            geometry={nodes.svgMesh3001.geometry}
            material={materials.mat_AR_controllerBlack}
            position={[0, -11.023, -5.979]}
            rotation={[0.43, 0, 0]}
          />
        </group>
        <mesh
          name="pCube120"
          castShadow
          receiveShadow
          geometry={nodes.pCube120.geometry}
          material={materials.mat_AR_glossyBlack}
          position={[0, 0.011, 0]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Black}
          position={[-0.496, 0, 0.169]}
          scale={10}
        />
        <mesh
          name="Plane001"
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Black}
          position={[0.064, 0, -0.246]}
          scale={[0.743, 1, 0.021]}
        />
        <mesh
          name="Plane002"
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.Black}
          position={[0.424, 0.505, -0.094]}
          scale={[0.497, 1, 0.158]}
        />
        <mesh
          name="Gas_Tank"
          castShadow
          receiveShadow
          geometry={nodes.Gas_Tank.geometry}
          material={materials.tank}
          position={[0.166, 0.585, -0.09]}
          rotation={[-3.138, 0, 0]}
          scale={[-0.027, -0.029, -0.032]}
        >
          <mesh
            name="Brake"
            castShadow
            receiveShadow
            geometry={nodes.Brake.geometry}
            material={materials.exhaust}
            position={[-0.402, 0.977, 1.16]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.025, 0.178, 0.026]}
          />
          <mesh
            name="Engine_1"
            castShadow
            receiveShadow
            geometry={nodes.Engine_1.geometry}
            material={materials.engine}
            position={[-0.065, -1.43, 0]}
            scale={[1.303, 1.1, 0.931]}
          />
          <mesh
            name="Engine_2"
            castShadow
            receiveShadow
            geometry={nodes.Engine_2.geometry}
            material={materials.engine}
            position={[2.301, -1.188, 0]}
            scale={[0.375, 0.351, 0.229]}
          />
          <mesh
            name="Engine_3"
            castShadow
            receiveShadow
            geometry={nodes.Engine_3.geometry}
            material={materials.engine}
            position={[1.983, -0.711, 0]}
            scale={[0.54, 0.505, 0.29]}
          />
          <mesh
            name="Engine_4"
            castShadow
            receiveShadow
            geometry={nodes.Engine_4.geometry}
            material={materials.engine}
            position={[2.201, -1.518, 0.964]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.402, 0.341, 0.376]}
          />
          <mesh
            name="Engine_5"
            castShadow
            receiveShadow
            geometry={nodes.Engine_5.geometry}
            material={materials.exhaust}
            position={[1.394, -0.67, 0]}
            rotation={[0.034, 0.039, -1.264]}
            scale={[0.167, 0.31, 0.139]}
          />
          <mesh
            name="Engine_6"
            castShadow
            receiveShadow
            geometry={nodes.Engine_6.geometry}
            material={materials.exhaust}
            position={[1.671, -1.044, 0]}
            scale={[0.116, 0.109, 0.099]}
          />
          <mesh
            name="Exhaust_left"
            castShadow
            receiveShadow
            geometry={nodes.Exhaust_left.geometry}
            material={materials.exhaust}
            position={[0.322, -0.826, -0.344]}
            rotation={[0, 0, 2.482]}
            scale={[-0.084, -0.477, -0.073]}
          />
          <mesh
            name="Exhaust_right"
            castShadow
            receiveShadow
            geometry={nodes.Exhaust_right.geometry}
            material={materials.exhaust}
            position={[0.322, -0.826, 0.34]}
            rotation={[0, 0, -0.659]}
            scale={[0.084, 0.477, 0.073]}
          />
          <mesh
            name="Front_bumper_left"
            castShadow
            receiveShadow
            geometry={nodes.Front_bumper_left.geometry}
            material={materials.engine}
            position={[-1.177, -0.563, -0.295]}
            rotation={[0, 0, -0.435]}
            scale={[0.095, 1.429, 0.08]}
          />
          <mesh
            name="Front_bumper_right"
            castShadow
            receiveShadow
            geometry={nodes.Front_bumper_right.geometry}
            material={materials.engine}
            position={[-1.177, -0.563, 0.293]}
            rotation={[0, 0, -0.435]}
            scale={[0.093, 1.308, 0.08]}
          />
          <group
            name="Front_lights"
            position={[-0.854, 0.429, 0.504]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.117, 0.125, 0.156]}
          >
            <mesh
              name="Cylinder026"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026.geometry}
              material={materials.exhaust}
            />
            <mesh
              name="Cylinder026_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026_1.geometry}
              material={materials.flash}
            />
          </group>
          <mesh
            name="Front_water"
            castShadow
            receiveShadow
            geometry={nodes.Front_water.geometry}
            material={materials.exhaust}
            position={[-1.526, -0.389, 0]}
            scale={[0.348, 0.326, 0.296]}
          />
          <group
            name="Front_wheel"
            position={[0, -3.182, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.097, 0.931, 1.026]}
          >
            <mesh
              name="Cylinder016"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder016.geometry}
              material={materials.tire}
            />
            <mesh
              name="Cylinder016_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder016_1.geometry}
              material={materials.engine}
            />
          </group>
          <mesh
            name="Front_wheel_inside"
            castShadow
            receiveShadow
            geometry={nodes.Front_wheel_inside.geometry}
            material={materials.exhaust}
            position={[0, -5.068, 0]}
            scale={[0.026, 0.622, 0.022]}
          />
          <group
            name="Gauges"
            position={[-0.374, 0.913, 0.187]}
            rotation={[0, 0, -0.694]}
            scale={[0.158, 0.115, 0.138]}
          >
            <mesh
              name="Cylinder010"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010.geometry}
              material={materials.exhaust}
            />
            <mesh
              name="Cylinder010_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder010_1.geometry}
              material={materials.gauge}
            />
          </group>
          <group
            name="Headlight"
            position={[-1.122, 0.517, -0.004]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.32, 0.342, 0.29]}
          >
            <mesh
              name="Cylinder007"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007.geometry}
              material={materials.exhaust}
            />
            <mesh
              name="Cylinder007_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007_1.geometry}
              material={materials.front_light}
            />
          </group>
          <mesh
            name="Licence_plate"
            castShadow
            receiveShadow
            geometry={nodes.Licence_plate.geometry}
            material={materials.plate}
            position={[4.942, -0.879, 0]}
            rotation={[0, 0, 0.358]}
            scale={[0.035, 0.242, 0.403]}
          />
          <mesh
            name="Main_shaft"
            castShadow
            receiveShadow
            geometry={nodes.Main_shaft.geometry}
            material={materials.engine}
            position={[-0.107, -0.647, -0.006]}
            rotation={[0, 0, 0.362]}
            scale={[0.12, 1.263, 0.103]}
          />
          <mesh
            name="rea_bumper_right"
            castShadow
            receiveShadow
            geometry={nodes.rea_bumper_right.geometry}
            material={materials.engine}
            position={[3.272, -1.12, 0.298]}
            rotation={[0, 0, 0.528]}
            scale={[0.101, 0.77, 0.083]}
          />
          <mesh
            name="Rear_bumper_left"
            castShadow
            receiveShadow
            geometry={nodes.Rear_bumper_left.geometry}
            material={materials.engine}
            position={[3.29, -1.12, -0.3]}
            rotation={[0, 0, 0.494]}
            scale={[0.101, 0.768, 0.083]}
          />
          <group
            name="Rear_light"
            position={[4.785, -1.888, 0]}
            scale={[1.097, 1.026, 0.931]}
          >
            <mesh
              name="Cylinder025"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025.geometry}
              material={materials.exhaust}
            />
            <mesh
              name="Cylinder025_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025_1.geometry}
              material={materials["rear light"]}
            />
          </group>
          <mesh
            name="Rear_water"
            castShadow
            receiveShadow
            geometry={nodes.Rear_water.geometry}
            material={materials.exhaust}
            position={[2.364, -0.711, 0]}
            scale={[1.097, 1.026, 0.931]}
          />
          <group
            name="Rear_wheel"
            position={[5.34, -3.182, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.097, 0.931, 1.026]}
          >
            <mesh
              name="Cylinder023"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder023.geometry}
              material={materials.tire}
            />
            <mesh
              name="Cylinder023_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder023_1.geometry}
              material={materials.engine}
            />
          </group>
          <mesh
            name="Rear_wheel_inside"
            castShadow
            receiveShadow
            geometry={nodes.Rear_wheel_inside.geometry}
            material={materials.exhaust}
            position={[5.27, -5.068, 0]}
            scale={[0.026, 0.622, 0.022]}
          />
          <mesh
            name="Seat"
            castShadow
            receiveShadow
            geometry={nodes.Seat.geometry}
            material={materials.seat}
            position={[2.541, 0.009, 0]}
            scale={[0.46, 0.411, 0.316]}
          />
          <group
            name="Steering"
            position={[-0.422, -0.761, 0.009]}
            rotation={[1.572, -0.194, -0.012]}
            scale={[1.095, 0.931, 1.028]}
          >
            <mesh
              name="Cylinder009"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009.geometry}
              material={materials.engine}
            />
            <mesh
              name="Cylinder009_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009_1.geometry}
              material={materials.seat}
            />
          </group>
        </mesh>
        <mesh
          name="Basketball"
          castShadow
          receiveShadow
          geometry={nodes.Basketball.geometry}
          material={materials.Basketball}
          position={[0.694, 0, 0.062]}
          rotation={[0.231, 0.888, -0.249]}
          scale={0.001}
        />
        <mesh
          name="vijncb3_LOD0_TIER0_000"
          castShadow
          receiveShadow
          geometry={nodes.vijncb3_LOD0_TIER0_000.geometry}
          material={materials.MatID_1}
          position={[0.732, -0.003, 0.012]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.007}
        />
        <group
          name="10517_Motorcycle_Helmet_v01_L3"
          position={[0.653, 0.475, -0.095]}
          rotation={[0.053, -0.015, -0.281]}
          scale={0.008}
        >
          <mesh
            name="10517_Motorcycle_Helmet_v01_L3_1"
            castShadow
            receiveShadow
            geometry={nodes["10517_Motorcycle_Helmet_v01_L3_1"].geometry}
            material={materials["10517_Motorcycle_Helmet_v01.001"]}
          />
          <mesh
            name="10517_Motorcycle_Helmet_v01_L3_2"
            castShadow
            receiveShadow
            geometry={nodes["10517_Motorcycle_Helmet_v01_L3_2"].geometry}
            material={materials["10517_Motorcycle_Helmet_v01_glass.001"]}
          />
        </group>
        <group name="~mJ=In1PK#2@M*G" rotation={[Math.PI / 2, 0, 0]} />
        <mesh
          name="stringing001"
          castShadow
          receiveShadow
          geometry={nodes.stringing001.geometry}
          material={materials["stringing.001"]}
          position={[0.021, 0.373, -3.086]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.011, 0.027, 0.011]}
        />
        <group
          name="ropes001"
          position={[0.003, 0.376, -3.086]}
          rotation={[0, 1.112, 0]}
          scale={[0.012, 0.004, 0.012]}
        >
          <mesh
            name="Cylinder056"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder056.geometry}
            material={materials.stringholderred}
          />
          <mesh
            name="Cylinder056_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder056_1.geometry}
            material={materials.stringsblack}
          />
        </group>
        <mesh
          name="handle002_Circle010"
          castShadow
          receiveShadow
          geometry={nodes.handle002_Circle010.geometry}
          material={materials["handle.002"]}
          position={[0.903, 0.198, -0.12]}
          rotation={[-0.483, -0.061, -1.21]}
          scale={0.07}
        >
          <mesh
            name="frame002_Circle000"
            castShadow
            receiveShadow
            geometry={nodes.frame002_Circle000.geometry}
            material={materials["frame.002"]}
          />
          <group name="ropes002_Cylinder057">
            <mesh
              name="ropes002_Cylinder057_1"
              castShadow
              receiveShadow
              geometry={nodes.ropes002_Cylinder057_1.geometry}
              material={materials.stringholderblack}
            />
            <mesh
              name="ropes002_Cylinder057_2"
              castShadow
              receiveShadow
              geometry={nodes.ropes002_Cylinder057_2.geometry}
              material={materials.stringswhite}
            />
          </group>
          <mesh
            name="stringing002_Cylinder001"
            castShadow
            receiveShadow
            geometry={nodes.stringing002_Cylinder001.geometry}
            material={materials["stringing.002"]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Love.glb");
